import 'package:app_tennis/data/models/tennis_courts_model.dart';
import 'package:app_tennis/data/models/tennis_courts_reservation_model.dart';

final List<TennisCourts> tennisCourts = [
  TennisCourts(
    id: '1',
    name: 'Epic Box',
    courtType: 'Cancha tipo A',
    availableDate: '2023-10-01',
    pricePerHour: '25.00',
    reserverdBy: '',
    timeReserved: '',
    location: 'Location 1',
    image: 'assets/images/epic_box.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: true,
  ),
  TennisCourts(
    id: '2',
    name: 'Rusty Tenis',
    courtType: 'Cancha tipo B',
    availableDate: '2023-10-02',
    pricePerHour: '25.00',
    reserverdBy: '',
    timeReserved: '',
    location: 'Location 2',
    image: 'assets/images/rusty_tenis.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: false,
  ),
  TennisCourts(
    id: '3',
    name: 'Cancha Multiple',
    courtType: 'Cancha tipo C',
    availableDate: '2023-10-02',
    pricePerHour: '25.00',
    reserverdBy: '',
    timeReserved: '',
    location: 'Location 2',
    image: 'assets/images/cancha_multiple.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: false,
  ),
];

final List<TennisCourtsReservedModel> tennisCourtsReserved = [
  TennisCourtsReservedModel(
    id: '1',
    name: 'Epic Box',
    courtType: 'Cancha tipo A',
    availableDate: '2023-10-01',
    pricePerHour: '25.00',
    reserverdBy: 'Jorge Cuello',
    timeReserved: '',
    dateReserved: '2023-09-18',
    location: 'Location 1',
    image: 'assets/images/epic_box.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: true,
    reservedHours: '2 horas',
    inittialHour: '7:00 am',
    finalHour: '4:00 pm',
    price: '25.00',
    instructor: 'Jorge Cuello',
  ),
  TennisCourtsReservedModel(
    id: '2',
    name: 'Rusty Tenis',
    courtType: 'Cancha tipo B',
    availableDate: '2023-10-02',
    pricePerHour: '25.00',
    reserverdBy: 'Jorge Cuello',
    timeReserved: '',
    location: 'Location 2',
    image: 'assets/images/rusty_tenis.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: false,
    dateReserved: '2023-10-01',
    reservedHours: '2 horas',
    inittialHour: '7:00 am',
    finalHour: '4:00 pm',
    price: '25.00',
    instructor: 'Jorge Cuello',
  ),
  TennisCourtsReservedModel(
    id: '3',
    name: 'Cancha Multiple',
    courtType: 'Cancha tipo C',
    availableDate: '2023-10-02',
    pricePerHour: '25.00',
    reserverdBy: 'Dairys Rangel',
    timeReserved: '',
    location: 'Location 2',
    image: 'assets/images/cancha_multiple.png',
    availableHours: 'de 7:00 am a 4:00 pm',
    isAvailable: false,
    dateReserved: '2023-10-01',
    reservedHours: '1 hora',
    inittialHour: '7:00 am',
    finalHour: '4:00 pm',
    price: '25.00',
    instructor: 'Dayana Rangel',
  ),
];
